function [ R ] = R_NtD( pkm,pkm_match,phim,phim_measure_noisy,...
                      x_source,S,x,y,xx,yy,nx,ny,xm,ym,lx,...
                      ly,l,r,theta,sanity,dim,stp,lambda_NtD )
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here
[ pkm_0,F1 ] = Sol_Poisson_BEM_Dirichlet(phim,...
                      x_source,S,x,y,xx,yy,nx,ny,xm,ym,lx,...
                      ly,l,r,theta,sanity,dim); 
                  
                  pkm0_match = pkm_0(1:stp:end);
                  R = norm(pkm - pkm_0,2)+...
                      lambda_NtD*norm(pkm_match - pkm0_match,2);
end

